spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/dnd_13th_5team_local
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:fake-kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:fake-kakao-client-secret}
            scope: ${KAKAO_SCOPE:profile_nickname,profile_image,account_email}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://fake-test-domain.com/oauth/callback}
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI:http://fake-kakao-auth.com/authorize}
            token-uri: ${KAKAO_TOKEN_URI:http://fake-kakao-token.com/token}
            user-info-uri: ${KAKAO_USER_INFO_URI:http://fake-kakao-userinfo.com/user}
            user-name-attribute: ${KAKAO_USER_NAME_ATTRIBUTE:id}


kakao:
  auth-url: ${KAKAO_AUTHORIZATION_URI:http://fake-kakao-auth.com/authorize}
  client-id:  ${KAKAO_CLIENT_ID:fake-kakao-client-id}
  redirect-url: ${KAKAO_REDIRECT_URI:http://fake-test-domain.com/oauth/callback}
  access-token-url: ${KAKAO_TOKEN_URI:http://fake-kakao-token.com/token}
  client-secret: ${KAKAO_CLIENT_SECRET:fake-kakao-client-secret}

jwt:
  secret: ${JWT_SECRET:testestsetstsetstetsetsetstsetsetset}
  access-expiration: ${ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${REFRESH_EXPIRATION:86400000}
