spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/dnd_13th_5team_local
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true